on: push
name: Notification
jobs:
  lsdTeamNotification:
    name: LSD Teams Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: LSD Teams
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CHANNEL }}
  lsdcommerceSlack:
    name: LSDCommerce Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: LSDComemrce Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
   