on: push
name: Notification
jobs:
  lsdTeamNotification:
    name: LSD Teams Notification
    id: lsdteam
    uses: slackapi/slack-github-action@v1.14.0
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_CHANNEL }}
  lsdcommerceNotification:
    name: LSDCommerce Notification
    id: lsdcommerce
    uses: slackapi/slack-github-action@v1.14.0
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}