on: push
name: Notification
jobs:
  lsdTeamNotification:
    name: LSD Team Notification
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.15.0
    - name: LSD Teams
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_CHANNEL }}

  lsdcommerceNotification:
    name: LSDCommerce Notification
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.15.0
    - name: LSDCommerce
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}