on: push
name: Notification
jobs:
  lsdTeamNotification:
    name: LSD Teams Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: LSD Teams
      uses: bryannice/gitactions-slack-notification@2.0.0
      env:
        SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CHANNEL }}
        SLACK_TITLE: 'LSDCommerce Push'
        
  lsdcommerceSlack:
    name: LSDCommerce Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: LSDComemrce Slack
      uses: bryannice/gitactions-slack-notification@2.0.0
      env:
        SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: 'LSDCommerce Push'
   